name: Terraform Infra CI/CD
run-name: Triggered By ${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches:
    - main 
    - develop
  pull_request:
    branches:
    - main 
permissions:
  id-token: write
  contents: read 
defaults:
  run:
    working-directory: ./
jobs:
  terraform_scan:
    name: Terraform Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v4
      
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v6
      with:
        tflint_version: v0.52.0
        cache: true
    - name: Show version
      run: tflint --version
    - name: Init TFLint
      run: tflint --init
      
  
  

  
    
