name: Using Variable Workflow
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
run-name: Triggered By ${{ github.actor }} | Branch: ${{ github.run_id }} | Run Id: ${{ github.run_id }}
env:
  cloud: Azure Cloud
jobs:
  My_First_Job:
    name: My First Job
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
    - name: Printing Message Using Variable On Linux Runner
      run: echo "$Greeting $User is using $cloud!"
      env:
        User: Sunil
  My_Second_Job:
    name: My Second Job 
    runs-on: windows-latest
    env:
      Abc: Hi
    steps:
    - name: Printing Message using Variable on Window Runner
      run: Write-Host "${{ env.Abc }} ${{ env.User }} is using ${{ env.cloud }}"
      env:
        User: Sushil
    
    
